# Site settings
title: Another Tamouse.Org Site
email: tamouse@gmail.com
description: |

  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: tamouse
github_username:  tamouse

# Build settings
markdown: kramdown
kramdown:
  input: GFM

exclude:
  - bin
  - CONTRIBUTOR_COVENANT.md
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - LICENSE.md
  - README.md

gems:
  - bootstrap-sass
  - jekyll-bootstrap-sass
  - jekyll-sitemap
