# Only need to include this when building the published site
# Run as jekyll build --config=_config.yml,_config_publish.yml

url: "http://tamouse.github.io" # the base hostname & protocol for your site
baseurl: "/jekyll-bootstrap-sidebar-starter-kit"
destination: _publish
